### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by Ivra23** [nenecmrf/OCPP-J-CP-Simulator#10]
Hello,
thank you for your example. 
I would like to know is the CP is on 5 digitsm, I have Legran station with serial S22-3-000146 but i can't connect with your application.
I change just CP and URL for the station ?
thanks

**Comment by kubarskii** [comment]
Hi, what server so you use?

**Comment by Ivra23** [comment]
Hi,
I use in windows WampServer with Apache 2.4.37
and in Raspberry pi Apache Maven 3.6.1.
Thank you.

**Comment by Ivra23** [comment]
Hello, In my Station i don't have ID tag and the IP adress it's 192.168.0.20 with subnet mask 255.255.248.0.

I test a lot of simulator find on github but no work with my station
it's correct ( ws://192.168.0.20:80/steve/websocket/CentralSystemService/test ) or it's IP adress of server and not the adress Station 

![image](https://user-images.githubusercontent.com/38098276/59778461-d1054f00-92b6-11e9-8c96-a818f119ee51.png)

Thanks

**Comment by kubarskii** [comment]
Suppose this is how your endpoint should look like: ws://192.168.0.20/steve/websocket/CentralSystemService/test
And possibly not 192.168.0.20 but localhost:port

According to docs: ws://your-server-ip:port/steve/websocket/CentralSystemService/chargeBoxId

**Comment by Ivra23** [comment]
Hello, 
And it's my localhost for my raspberry ?
because i don't understand if (your server ip : port) it's charging point or Raspberry
thanks

**Comment by kubarskii** [comment]
It's the endpoint of your server

**Comment by Ivra23** [comment]
Hello,

Thank you for replay :) 
After installing the image of steve on raspberry pi B 3+, I was able to connect via your simulator to the charging station, Now I am trying to send commands to the charging station
Are there any actions to say "Start charging of vehicle" and "Stop charging of vehicle "?

![image](https://user-images.githubusercontent.com/38098276/60342446-bf583180-99b1-11e9-9d60-5eed2153d218.png)

Knowing that my terminal does not have any idtag

Thank you,

**Comment by kubarskii** [comment]
actually, there is start/stop transaction, and you can call remoteStart/StopTransaction from the server

**Comment by Ivra23** [comment]
I tried to press start / stop transaction but it doesn't work (I have no modification at the charging point) you have an idea why?
thank you

**Comment by kubarskii** [comment]
that can be caused by changes in the protocol, it'd be nice if you check the standart. I suppose there were changes in namings
