### ISSUE TITLE
Improvement: add multiconnecter support

### ISSUE THREAD

**Issue by henrywah196** [nenecmrf/OCPP-J-CP-Simulator#2]
Good job! Please improve to add multi connector support.

**Comment by kubarskii** [comment]
Will work on it. I believe it wont take long.

**Comment by kubarskii** [comment]
@henrywah196 Did some changes. You may try to check it. It's a bit hacky and needs refactoring but works.

**Comment by henrywah196** [comment]
nice. I'll give it a try. good job!
