### ISSUE TITLE
license

### ISSUE THREAD

**Issue by cyrine28** [nenecmrf/OCPP-J-CP-Simulator#9]
Hi 

how can i do to get the license please d

thanks

**Comment by psnehanshu** [comment]
What do you mean? It's open source and the licence is here https://github.com/nenecmrf/OCPP-J-CP-Simulator/blob/master/LICENSE

**Comment by cyrine28** [comment]
hi
thank you for your  response  so i  can it to do some test on a charge
point working on ocpp 1.6 protocol

cyrine

**Comment by psnehanshu** [comment]
Why don't you people work on OCPP 2.0. since it's released?

**Comment by cyrine28** [comment]
because i work on a charging point that works only on 1.6
